name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: [ruby-head, '3.1', '3.0', '2.7', '2.6']
        rails_version: ['edge', '7.0', '6.1', '6.0', '5.2']

        exclude:
          - ruby_version: ruby-head
            rails_version: '6.0'
          - ruby_version: ruby-head
            rails_version: '5.2'
          - ruby_version: '3.1'
            rails_version: '6.0'
          - ruby_version: '3.1'
            rails_version: '5.2'
          - ruby_version: '3.0'
            rails_version: '5.2'
          - ruby_version: '2.6'
            rails_version: 'edge'
          - ruby_version: '2.6'
            rails_version: '7.0'

    runs-on: ubuntu-latest

    env:
      RAILS_VERSION: ${{ matrix.rails_version }}

    steps:
    - uses: actions/checkout@v3

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true

    - run: bundle exec rake
