name: Ruby

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        ruby_version: ['3.0', '2.7', '2.6']
        rails_version: ['6.1', '6.0', '5.2']

        exclude:
          - ruby_version: '3.0'
            rails_version: '5.2'

    runs-on: ubuntu-latest

    env:
      RAILS_VERSION: ${{ matrix.rails_version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake
